
# Default values for custom-application.
# This is where you can set customizable values.

replicaCount: 1

wasImage:
  repository: "ekchoi3912/cicdlab_1"
  tag: "v1"
  pullPolicy: IfNotPresent


image:
  repository: nginx
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

# ingress:
#   enabled: true
#   annotations: {}
#   hosts:
#     - host: www.frodo.kr
#       paths: []
#   tls: []


